repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: requirements-txt-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: double-quote-string-fixer
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
  - repo: https://github.com/ambv/black
    rev: 21.4b0
    hooks:
      - id: black
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
default_language_version:
  python: python3.8
exclude: ^(layers/.*)
